In [1]:
import numpy as np
from sklearn.metrics import confusion_matrix
from sklearn import datasets


/usr/lib/python3.5/importlib/_bootstrap.py:222: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)


In [65]:
def fit(x_train,y_train):
    result = {}
    result['total_data'] = len(y_train)
    for current_class in set(y_train):
        result[current_class] = {}
        result[current_class]['total'] = (current_class == y_train).sum()
        for feature in range(len(x_train[0])):
            result[current_class][feature] = {}
            for different_values in set(x_train[:,feature]):
                result[current_class][feature][different_values] =  (x_train[y_train == current_class,feature] == different_values).sum()

    return result
fit(iris.data,iris.target)

{0: {0: {1.0: 50, 2.0: 0},
  1: {1.0: 8, 2.0: 42},
  2: {0.0: 48, 1.0: 2, 2.0: 0, 3.0: 0},
  3: {0.0: 49, 1.0: 1, 2.0: 0, 3.0: 0},
  'total': 50},
 1: {0: {1.0: 24, 2.0: 26},
  1: {1.0: 42, 2.0: 8},
  2: {0.0: 0, 1.0: 7, 2.0: 43, 3.0: 0},
  3: {0.0: 0, 1.0: 10, 2.0: 39, 3.0: 1},
  'total': 50},
 2: {0: {1.0: 6, 2.0: 44},
  1: {1.0: 33, 2.0: 17},
  2: {0.0: 0, 1.0: 0, 2.0: 31, 3.0: 19},
  3: {0.0: 0, 1.0: 0, 2.0: 5, 3.0: 45},
  'total': 50},
 'total_data': 150}

In [27]:
iris = datasets.load_iris()
for col in range(len(iris.data[0,:])):
    label(iris.data[:,col])
# iris.data

In [68]:
def probability(dictionary,current_class,row):
    output = dictionary[current_class]['total']/dictionary['total_data']
    for feature in row:
        output *= dictionary[current_class][feature][row[feature]]/dictionary[current_class]['total']
    return output

In [52]:
def predict_single(dictionary,row):
    classes = list(dictionary.keys())
    total = dictionary['total_data']
    best_p = -10000
    best_class = -1
    for current_class in classes:
        if (current_class == "total_data"):
            continue
        else:
            current_p = probability(dictionary,current_class,row)
            if current_p > best_p:
                best_p = current_p
                best_class = current_class
    return best_class

In [53]:
def predict(x_test,dictionary):
    y_pred = []
    for x in x_test:
        x_class = predict_single(dictionary,x)
        y_pred.append(x_class)
    return y_pred

In [54]:
def label(column):
    limit1 = column.mean()*0.5
    limit2 = column.mean()
    limit3 = column.mean()*1.5
    for entry in range(len(column)):
        if column[entry] <=limit1:
            column[entry] = 0
        elif column[entry] <=limit2 and column[entry] > limit1:
            column[entry] = 1
        elif column[entry] <= limit3 and column[entry] > limit2:
            column[entry] = 2
        elif column[entry] >limit3:
            column[entry] = 3
    return column

In [55]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(iris.data,iris.target,train_size = 0.8,random_state = 40)

/home/sidkathuria14/.local/lib/python3.5/site-packages/sklearn/model_selection/_split.py:2026: FutureWarning: From version 0.21, test_size will always complement train_size unless both are specified.
  FutureWarning)


In [66]:
dictionary = fit(x_train,y_train)

In [69]:
y_pred = predict(x_test,dictionary)

/home/sidkathuria14/.local/lib/python3.5/site-packages/ipykernel_launcher.py:4: VisibleDeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  after removing the cwd from sys.path.


In [79]:
from sklearn.metrics import confusion_matrix,classification_report
cm = confusion_matrix(y_pred,y_test)
cr = classification_report(y_pred,y_test)
print(cr)
print(cm)

             precision    recall  f1-score   support

          0       0.75      1.00      0.86         6
          1       1.00      0.86      0.92        14
          2       1.00      1.00      1.00        10

avg / total       0.95      0.93      0.94        30

[[ 6  0  0]
 [ 2 12  0]
 [ 0  0 10]]
