In [12]:
import numpy as np
from sklearn import datasets
import matplotlib.pyplot as plt
from collections import Counter

In [3]:
iris = datasets.load_iris()

In [4]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(iris.data,iris.target,test_size = 0.2,random_state = 0)

In [5]:
from sklearn.neighbors import KNeighborsClassifier
model = KNeighborsClassifier()
model.fit(x_train,y_train)
y_pred = model.predict(x_test)

In [9]:
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report
cm = confusion_matrix(y_pred,y_test)
cr = classification_report(y_pred,y_test)
print(cr,cm)

             precision    recall  f1-score   support

          0       1.00      1.00      1.00        11
          1       0.92      1.00      0.96        12
          2       1.00      0.86      0.92         7

avg / total       0.97      0.97      0.97        30
 [[11  0  0]
 [ 0 12  0]
 [ 0  1  6]]


## Self functions from scratch

In [11]:
def predict(x_train,y_train,x_test,k):
    y_pred = []
    
    
    for x_point in x_test:
        y_pred.append(predict_single(x_train,y_train,x_point,k))
    return y_pred

In [22]:
def predict_single(x_train,y_train,x_row,k):
    distances = []
    for index in range(len(x_train)):
        distance = ((x_train - x_row)**2).sum()
        distances.append([distance,index])
#         (distances)
    distances = sorted(distances)
    targets = []
    for i in range(k):
        targets.append(y_train[distances[i][1]])
    return Counter(targets).most_common(1)[0][0]

In [23]:
predict_single(x_train,y_train,x_test[0],7)

2

In [24]:
pred = predict(x_train,y_train,x_test,7)

In [25]:
conf = confusion_matrix(y_pred,y_test)
conf

array([[11,  0,  0],
       [ 0, 12,  0],
       [ 0,  1,  6]])